server:
  port: 8764
spring:
  application:
    name: service-another
eureka:
  instance:
    #服务实例
    hostname: 127.0.0.1
    #租期更新时间间隔（默认30秒）
    #lease-renewal-interval-in-seconds: 10
    #租期到期时间（默认90秒）不怕出错的话，时间可以更短
    #lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
          defaultZone: http://127.0.0.1:8761/eureka/
    #开启健康检查（需要spring-boot-starter-actuator依赖）
    #healthcheck:
      #enabled: true
